label Act1:
    "We see Amber and Marina in a pawn shop with Marina pleading Amber to buy her a strange device."
    Marina "Come on Amber! it looks so interesting"
    Amber "Marina I said no! we don't even know what it does!"
    "Marina tries to use her puppy dog eyes on Amber"
    Amber "Marina, the seller doesn't even know what that thing is!"
    Marina "He knows what it's called! it’s a... er... what’s the name again?"
    seller "The skitso who sold it to me called it the InterdimensionalGregifcationTransportationCreation. bit of a handful but as far as i can tell, it just shows pretty lights and a screen with some text on it, it’s not that dangerous."
    "Marina tries to pronounce the devices name but fails"
    Marina "Can we please get the Greg Amber?"
    "Amber knows Marina isn't going to let this go and gives in"
    Amber "Fine, how much for it?"
    seller "50 bucks, it's got some kind of computer in it but I can't make heads or tails of it."
    Amber "25 and you've got a deal."
    seller "Deal"
    "The seller gives Marina the device and Amber pays him, the duo go back to the RV and Marina starts to play with it."
    Marina "Hey Amber, what’s a DUIDN?"
    Amber "What?"
    Marina "It says to select or input one."
    Amber "I don't know, put in a random one or select from one already programmed in."
    Marina "Ok"
    "Marina inputs the preset called FG-01_PRIME"
    IGTCitem "Destination set ready to phase."
    Marina "Oh, cool it talks!"
    Amber "Marina, back away from it."
    "Marina presses the green button labelled 'phase'"
    IGTCitem "Phasing."
    "The IGTC starts to glow and vibrate and a flash of white light, the RV is transported."
    Amber "WHAT THE HELL WAS THAT?!"
    Marina "oooo pretty lights."
    IGTCitem "Phasing complete. Warning device battery low, please recharge the InterdimensionalGregifcationTransportationCreation for continued use."
    Amber "What. Was. That."
    Marina "I think it phased."
    Amber "I’m taking that thing back for a refund."
    Marina "Amber wait!"
    "Amber steps out of the RV and stops right in her tracks"
    Amber "Where the hell are we?"
    "Amber and Marina do not see the pawn shop and the carpark that they were in. instead they see a cream house, with a texture that they've never seen before."
    Marina "Why does it look different to us?"
    Amber "I don't know, but we should go back inside the RV."
    unknown_voice_1 "Hey! What the heck are ya doin' on my frickin' lawn?!"
    "The unknown voice stomps up and it's a fat man with glasses"
    unknown_man_1 "I just frickin' had it reseeded, and let me tell ya, it wasn't frickin' cheap!"
    "Amber steps Infront of Marina with her arm extended, protecting her."
    Amber "Hey! we didn't know!"
    "Another unknown voice walks up"
    unknown_voice_2 "Oh, Peter! What the heck is happening out there, huh? Are there some crazy shenanigans or another one of your absurd adventures? Geez, I swear, sometimes I feel like I'm the only one keeping this family from falling apart!"
    Peter "Uh, Lois, I swear it's not another one of my crazy adventures! There are these, uh, kinda strange-looking girls on the grass outside."
    Marina "Hey! I do not look weird! You're the one with that black outline over you!"
    Peter "Huh? Black outline? What the heck are you talking about?"
    Marina "The black outline around you."
    "Peter looks at himself and Lois looks at herself"
    Peter "I don't see any black outline anywhere. Am I missing something here?"
    "Amber starts to look at the device trying to figure out if it has any answers"
    Marina "No no, it's right there."
    IGTCitem "Interactive help system activated. Please state your questions."
    Peter "Whoa, what the heck is that thing?!"
    IGTCitem "This unit is the, InterdimensionalGregifcationTransportationCreation, a device that allows its user to transport between dimensions."
    Amber "Wait, so are we in a different universe?"
    IGTCitem "Correct, the current universe is FG-01_PRIME"
    Peter "Hold on a sec, are you telling me there are other universes out there? Like, seriously? This is blowing my mind!"
    Lois "Oh, great! Other universes, really? Peter, this is starting to sound like another one of your wild escapades. I mean, come on, can't we just have a normal, quiet day for once? I swear, every time you get involved in something, it turns into a chaotic mess!"
    Amber "Oh, good we can get home. So how do we charge it?"
    IGTCitem "The unit can be charged via its type-c port on the back."
    Marina "What’s a type-c port?"
    Amber "I think it's the cable that I use for my phone."
    Marina "I think we'll get out of your hair now. Bye!"
    "Marina and Amber speedwalk to the RV, hoping to end their encounter"
    Peter "Look, Lois, it didn't turn into one of my crazy adventures after all!"
    unknown_man_2 "Hey, Peter! I stumbled upon some ducks packin' heat. You feel like swingin' by?"
    Peter "Oh, absolutely, Joe! Those ducks are in for some serious trouble!"
    "In the RV, Amber has plugged in the IGTC, and is trying to figure out how to get home."
    Amber "Why won't it select our universe?"
    Marina "Maybe somethings wrong? Hey Greg, why won't you select our universe?"
    IGTCitem "The last universe is unavailable, due to an unknown source blocking access to it."
    Marina "Maybe someone else in another universe can help us?"
    Amber "No Marina! We're already in a place we don't know! Going head first into another is begging for trouble!"
    Marina "But..."
    Amber "No buts! I love you, but I don't want to put you in danger."
    "Marina sulks a bit and Amber gets frustrated trying to find a way to undo the block from the IGTC."
    Amber "arggg, where would an unblocking function hide…"
    IGTCitem "No unblocking function available. other courses of action recommended."
    Amber "And what would you suggest?"
    IGTCitem "An individual familiar with the IGTC and dimension mechanics is recommended. One such individual is Dell Conagher, since he helped with the creation of the second IGTC prototype."
    Amber "And where is he?"
    IGTCitem "Dimension TF2-03_ALT, Bee Cave Texas, USA."
    "Amber thinks for a moment and Marina leans in."
    Amber "Yes, you were right."
    Marina "I know my ideas aren’t always the best but maybe bad ideas are what we really need."
    "Amber sighs"
    Amber "I’m sorry for yelling at you and shutting you down, I know I promised I would try to stop that."
    Marina "Its ok. we're in over our heads and you’re feeling overwhelmed. its ok to feel like that."
    Amber "Doesn’t excuse how I treated you."
    Marina "I forgive you Amber."
    Amber "Thanks Marina."
    Marina "Greg, take us to dell in bee cave!"
    IGTCitem "Destination set, phasing."
    return