label Act2:
    "in a white flash, the RV appeared in an outback desert next to a mountain, with a single cabin built into said mountain."
    "the girls get out of the RV and walk to the cabin. IGTC in hand they knock on the door and a voice answers:"
    unknown_voice_1 "Hold your horses, I'm fixin' to open the door for ya!"
    "the door opens."
    unknown_man_1 "Who in tarnation? Is that the IGTC?"
    Amber "it told us that you might know how to undo the block on our universe."
    unknown_man_1 "Well, I reckon I might be able to oblige, but I ain't promisin' nothin'. Git on in here, partner, 'fore the sun turns ya into a crispy critter."
    "the duo walk in and it’s a modest living space with what appears to be a workshop in another room."
    unknown_man_1 "Dell Conagher, pleased to meet ya. Y'all can just call me Dell. Go on and take a load off, partner."
    "Marina and Amber pull up a chair and dell brings a jug of cold water and some glasses over."
    Amber "thank you."
    TF2Engie "Well, darlin', it ain't nothin' to worry 'bout, ladies. Now, let's get down to brass tacks. How in tarnation did y'all cross paths with the IGTC?"
    Amber "Marina found it at a pawn shop."
    Marina "the seller said that the dude who sold it to him was a skitso or something?"
    "Dell sighs"
    TF2Engie "his ailments have taken a turn for the worse."
    Amber "who's?"
    TF2Engie "The fella behind the IGTC. Kevin."
    Marina "what’s skitso?"
    TF2Engie "Schizophrenia, a downright nasty mental hitch that poor Kevin got dealt. Seems like he done gone and lost it, a real shame. His knack for quantum mechanics was somethin' else, I'll tell ya."
    Marina "when we can get back to our universe, we might be able to find and help him."
    Amber "if we can get to our universe."
    TF2Engie "Well, now, my expertise in the medical realm stops at the physical side of things. His condition, well, it's one of them rarer types of schizophrenia that just won't budge with the usual meds. I reckon I ain't got enough know-how to give him the right kind of help."
    Marina "do you know anyone who could help?"
    TF2Engie "I know a fella, a bit unpredictable, mind ya. He's got the know-how, but he don't give a hoot if his patient's teetering on the edge of kickin' the bucket. Sees it as some sorta \"invaluable medical knowledge\" if you can believe that."    
    TF2Engie "Anyhow, I gotta figure out how this universe of yours is gettin' blocked, IGTC. Fire up them universe scan databases and dig for any recent hiccups or troubles."
    IGTCitem "searching. search complete. universe HB-05_ALTERNATE is unavailable."
    TF2Engie "Why in tarnation is it unavailable?"
    IGTCitem "a cosmic block has been put up, source of block unknown."
    TF2Engie "Cosmic block? Why in the blazes would some cosmic hombre shut the door on accessing that universe?"
    Amber "what’s a cosmic block?"
    TF2Engie "In plain speak, it's like a blockade set up by a cosmic feller to keep folks outta that universe. There's gotta be some cosmic hitches happening in your neck of the woods for it to be all locked up like that."
    Marina "what’s a cosmic feller?"
    TF2Engie "A fella with the ability to harness cosmic powers, y'see. Picture god-like abilities, but without the whole deity business."
    Marina "ahhhhhh"
    Amber "so, some asshole is blocking our universe."
    TF2Engie "Regrettably, yes. There are ways to undo this mess, but I gotta have a chat with a buddy in a whole other universe. My know-how on cosmic folks is a bit limited, you see."
    Marina "what’s his name?"
    TF2Engie "Her name's GLaDOS, a mighty powerful A.I. with a better grip on cosmic beings than I do. She ain't exactly fond of strangers in her territory, but given the situation, she oughta understand."
    Amber "ok, we'll go and visit GLaDOS and see what she can do."
    TF2Engie "Well then, I reckon I'll mosey on and fetch some of my gear. If you ladies could toss them glasses in the sink and stow away the jug in the icebox, I'd sure appreciate it."
    Marina "that we can do!"
    "Amber and Marina put the jug and glasses away and wait for dell at the front door. dell has a hardhat, goggles and a backpack on while holding a toolbox in one hand and a golden wrench in another."
    Marina "oooo pretty gold..."
    TF2Engie "This here wrench? Gift from a wizard, goes by the name of Merasmus. Anyways time to hustle, gotta secure things up 'fore we hit the multiversal road."
    "the girls and dell exit the house and dell locks up, they proceed to enter the RV and dell puts his stuff down and starts programming the IGTC."
    TF2Engie "Well, ain't this RV a sight for sore eyes? Way tidier than the last one I found myself in; that ol' thing always reeked of urine."
    Marina "ew."
    IGTCitem "destination set, universe POR-01_PRIME, phasing."
    return