label Act3:
    "in a flash of white the RV was teleported away from the dust and heat of the desert. the new place was cold, clinical, ominous and smelt like cleaning supplies were used daily."
    "a voice booms over them as if it was the place itself talking."
    unknown_voice_3 "Well, it appears we have an unexpected visitor in Test Chamber 14 – an RV, of all things."
    "the RV door opens and dell and the girls step out."
    TF2Engie "Well now, pardon the interruption, GLaDOS. My apologies, my phone ain't quite equipped for them interdimensional calls otherwise i'd call."
    GLaDOS "Greetings, Dell. It's mildly tolerable to encounter your presence. I notice you've brought along a collection of companions."
    TF2Engie "Amber and Marina here, their universe is locked up tight by some cosmic bigwig. The IGTC's bit hazy on details. Figured those interdimensional sensors you're cookin' up might shed some light on the situation."
    GLaDOS "Regrettably, the Aperture Science multidimensional sensors are experiencing a phase of imperfection."
    TF2Engie "the IGTC's got a backlog of data since it was put together, 'bout five years worth. reckon that might come in handy for finishing them sensors."
    GLaDOS "an intriguing proposition. Leveraging the data housed within the IGTC could indeed expedite the completion of the sensor development process."
    TF2Engie "I reckon I can even throw in a hand with the project, partner. Fresh eyes on a thing tend to do wonders, don't they?"
    GLaDOS "Indeed, they do. A hand with the project would be most beneficial. I'm programming the test chAmber 14 elevator to transport you to the central core chAmber. We shall proceed from that point."
    TF2Engie "I'll fetch my gear from the RV real quick, shouldn't be more than a jiffy."
    GLaDOS "No need for unnecessary complications; I'll bring the RV here. Efficiency is paramount."
    TF2Engie "got it."
    "dell and the duo walk to the elevator which takes them to the chamber."
    "there in all her glory, is GLaDOS herself. with the RV off to the side."
    "Amber and Marina are in awe of GLaDOS's size."
    Amber "I’m at a loss for words."
    "Marina cheery as ever, says hello in her own way."
    Marina "Hi! I’m Marina and this is Amber, you look so big! is your name from your mom's side or your dad's? it’s such a pretty name and I love it-{nw}"
    GLaDOS "please stop."
    Marina "oh, uh sorry."
    GLaDOS "While your acknowledgment is duly noted, you should be aware that a deceleration in your pace is imperative."
    Marina "huh?"
    GLaDOS "slow down."
    Marina "ohhhhhh"
    GLaDOS "I understand your intention to engage in casual conversation, there are more urgent matters that require our attention."
    TF2Engie "Well now, partner, reckon you still got them old IGTC debug cables stashed away in your storage, GlaDOS?"
    GLaDOS "Aperture Science adheres to the principle of resource efficiency; the equipment is on its way as we speak."
    "right on cue the cable arrives and dell connects it to a spare core receptacle."
    GLaDOS "Have you received any communication from Kevin?"
    TF2Engie "From what them gals been talkin' 'bout, sounds like his Schizophrenia's taken a turn for the worse. Can't rightly tell if he's graspin' what's goin' on 'round him anymore."
    Amber "the seller who sold it didn't say much, I doubt he cared about his condition."
    GLaDOS "The exploration into Kevin's distinctive manifestation of schizophrenia has advanced to a stage where I can momentarily stabilize his condition. However, a more enduring solution remains elusive."
    Marina "I hope he's ok."
    TF2Engie "Kevin's one tough hombre, partner. He'll pull through, you can count on that."
    GLaDOS "The data from the IGTC is proving beneficial, allowing me to attain a more defined understanding, although the overall picture remains somewhat indistinct."
    Amber "so, who's blocking our universe?"
    GLaDOS "Contrary to the IGTC's explanation, the compiled data suggests a hindrance from numerous formidable entities. The precise reasons for their interference and the nature of these entities remain elusive, defying detailed comprehension."
    Marina "so, what do we do?"
    GLaDOS "The most prudent course of action seems to involve direct interaction. Venturing into the interdimensional space between dimensions appears to be the optimal strategy, as the data indicates this is the locus of their obstructive activities."
    Amber "so how do we get there?"
    TF2Engie "Well now, looks like we're in need of some wheels. GLaDOS, by any chance do you have a spare vehicle lyin' around?"
    GLaDOS "Regrettably, there's no available option, at least not one equipped to accommodate the necessary modifications."
    TF2Engie "Them gals' RV oughta have plenty of room for what we need."
    Amber "that’s my Gramp’s RV! i don't want anyone doing any kind of science projects on it!"
    GLaDOS "While I comprehend your sentiment toward your RV, a substitute is not readily available. Constructing a suitable alternative poses a prolonged challenge, given that the facilities capable of such production are currently undergoing refurbishment."
    Amber "but..."
    GLaDOS "The cosmic entities in question might extend their influence beyond mere interference, potentially posing a threat to the well-being of your universe. Lives could be in jeopardy due to their actions."
    "Amber thinks for a minute"
    Amber "fine. but when this is done I want the modifications undone!"
    GLaDOS "Acknowledged. Dell, initiate the disassembly process for the IGTC. I will commence the design and fabrication of the required components for the RV's upgrade."
    TF2Engie "The current quantum processor in the IGTC ain't cuttin' it for the extra phasing emitters we're throwin' in. Gonna need somethin' else to link up with the IGTC and take control proper-like."
    GLaDOS "A spare core could suffice; I’m retrieving one from storage. As for the girls, while I work on crafting the interface for the core, please apprise the core herself of the current situation."
    Amber "huh?"
    "a core lifts up from the ground and activates."
    unknown_core_1 "Huh? wait where am I? who are you?"
    Marina "hi I’m Marina, this is Amber! GLaDOS said you're going to be some kind of controller for the Greg!"
    unknown_core_1 "what?"
    Amber "I haven't got a better explanation for you."
    unknown_core_1 "oh, uh ok. I’m Alice, nice to meet you."
    Marina "you too!"
    Alice "I haven't seen humans here in a long time! not since the incide-"
    "Alice quietens down."
    Marina "what incident?"
    GLaDOS "I will respond to that. In a distant past, I harboured intense resentment towards my predicament and instigated a genocide against the human occupants within the facility."
    "Amber and Marina are horrified"
    GLaDOS "It's crucial to bear in mind that this occurred in the distant past, and I am not the same AI as before. The passage of time has gradually eroded away my anger, and I no longer endorse the actions I once took."
    GLaDOS "Kevin played a pivotal role in helping me recognize that, despite the imperfections of individual humans or groups, they do not embody the entirety of the species."
    GLaDOS "Although a dislike for humans persists within me, I no longer harbor hatred towards them."
    Amber "what happened to you to go to such lengths?"
    GLaDOS "Numerous facets to my experiences, Amber. but delving into the details of the subject would be both disheartening and time-consuming."
    Marina "I’m sorry for what happened to you."
    GLaDOS "I appreciate it, Marina. That chapter was in the distant past, and it's wisest to leave it behind."
    TF2Engie "{i}*ahem*{/i} pardon the interruption, but all the ruckus is done and dusted. Time to commence the buildin'."
    GLaDOS "This process will require a considerable amount of time. Alice, during the RV upgrade, please instruct the girls on how to operate the vehicle with its new modifications."
    Alice "can do!"
    "GLaDOS and dell work on the RV while Alice teaches the duo how to drive the RV."
    "after 2 hours the RV is finished. its main modifications are the wires and equipment on its exterior along with wings and an engine, an upgraded infotainment system with a core receptacle and a new steering wheel."
    GLaDOS "Amber, kindly establish a connection between Alice and the core receptacle in the RV to facilitate the activation of the upgraded IGTC."
    "Amber grabs Alice and enters the RV with Marina and dell then connects Alice to the upgraded infotainment system."
    Alice "ok activating IGTC."
    "the RV powers up with an electronic hum."
    GLaDOS "Leveraging the IGTC data, I've devised a communication method. We'll stay connected, allowing me to observe and listen to your surroundings."
    TF2Engie "I've punched in the coordinates. Alice, go ahead and do the honors, ma'am."
    Alice "will do!"
    "the RV powers up and disappears in a flash of white."
    return