label Act4:
    "the girls and dell see a world of bubbles containing universes. with some strange energy sounding one."
    "the wings on the RV fold open."
    Marina "that looks to be our universe."
    Amber "I see it."
    "Amber presses on the gas and the RV starts to fly there."
    "as they get closer Marina notices something."
    Marina "what are those star looking dudes?"
    Amber "I see them."
    GLaDOS "I'm uncertain. There are numerous entities and species exhibiting a skin pattern resembling stars, which is rather fascin-{nw}"
    "GLaDOS stops"
    GLaDOS "Depart from that location immediately!"
    Amber "what why?"
    GLaDOS "Celestialsapiens are an exceptionally dangerous and powerful species! they have absolute omnipotence, and remain utterly indifferent to our exist-{nw}"
    "GLaDOS cuts out and a celestialsapien grabs the RV with his fingers and squints."
    unknown_celestialsapien_1 "you are not supposed to be here. the decision was final."
    Amber "what decision? we just want to get to our universe!"
    unknown_celestialsapien_1 "your universe is being erased; its existence is causing damage to other universes."
    Marina "WHAT?!"
    Amber "what about the people who live there?! WHAT ABOUT THEM?!"
    unknown_celestialsapien_1 "their existence is inconsequential."
    Marina "that’s not fair!"
    TF2Engie "Well, slap my circuits! You celestial folks, pullin' off them stunts, that's a clear violation of the Multiversal Preservation Act! There gotta be other ways to put a stop to the damage without causin' chaos in other universes! Kevin's right smack in the middle of that universe, and he might just cook up a solution to this whol-{nw}"
    unknown_celestialsapien_1 "ENOUGH! the decision has already been made."
    "suddenly a surge of energy comes from the RV and pushes the celestialsapien away."
    Alice "sorry about that."
    Marina "we need to go and get Kevin!"
    Amber "agreed."
    "Amber steps on the gas and flies into their universe."
    Alice "where do you want the destination?"
    Amber "Las Vegas, we got the IGTC there so there’s a chance Kevin is still there."
    Alice "got it, destination set."
    "the celestialsapien tries to grab the RV but it’s too late. it’s already gone into their universe."
    "a flash of white light appears and the RV flies towards Las Vegas."
    Alice "the best way I can find him is if I scan for him. although with all these people I can only get an approximate location, if I had a DNA sample of him. which I don’t."
    TF2Engie "Given that Kevin ain't from this neck of the woods, his genetic makeup's is a whole different ballgame compared to the locals. Harness that distinct genetic makeup of Kevin's to fine-tune the scan. We'll track him down faster than a rabbit in a carrot patch."
    Alice "got it." 
    Alice "I think I’ve gotten his approximate location. its somewhere next to a pyramid shaped building. that’s all I got."
    Amber "it’s better than nothing."
    "the RV sets down next to a familiar RV but the duo don’t have time to think about it. dell grabs Alice and they all exit the RV."
    Amber "me and Marina will go this way, you and Alice to that way!"
    "the group separates and starts to look around. after a minute Amber and Marina hear something."
    unknown_man_2 "YOU WILL NOT GET THE PLATE OF DAWN FOR IT BELINGS TO KING DMV!"
    unknown_female_1 "Give me back that licence plate or ill beat your ass!"
    "the duo goes to have a look and they see three familiar faces and one homeless man with a different look then everyone else."
    Marina "Kevin..."
    Joseph "girls? what are you doing here?"
    Tess "Marina?"
    Mariah "what the hell are you dorks doing here?"
    TF2Engie "we caught wind of all that ruckus! What in tarnation is happenin' 'round her- Kevin?"
    "Kevin stares at dell, crazed eyes scanning him to ascertain if he is a threat."
    "dell gives Alice to Amber and holds out his hand to Kevin, trying to calm him as if he was a wild animal."
    TF2Engie "Kevin, your noggin's playin' tricks on ya. GLaDOS got them meds to wrangle that scatterbrained situation of yours, at least for a spell."
    Kevin "STAY BACK! THE EMPEROR WILL GET HIS DOOR FRAMES!"
    "Kevin pulls out a gun, it powers up and starts to spark violently."
    Tess "cool."
    Marina "maybe in a sci-fi tv show."
    "suddenly the ground starts the shake and the sky tears open like paper, revealing a celestialsapien."
    unknown_celestialsapien_1 "the decision is final!"
    "Mariah takes this opportunity to disarm Kevin, causing him to drop the licence plate and his gun, destroying the gun in the process, and falls onto the ground knocking him unconscious."
    TF2Engie "Marina, hustle up and snatch Kevin, we're headin' back to the RV in a jiffy!"
    "Marina grabs Kevin and they start to run back to their RV."
    Mariah "get back here I haven’t finished beating his ass!"
    "Mariah follows them and Joseph and Tess follow in suit."
    "they enter the RV and Mariah busts inside with Joseph and Tess behind her. Amber starts the RV and the RV flies off, dell connects Alice to the RV."
    Alice "setting destination!"
    "the celestialsapien again tries to grab the RV but in a flash of white the RV disappears, leaving behind the screams of Las Vegas and an annoyed cosmic being."
    return