label Act5:
    "act 5"
    "the RV appears in the facility and just before it’s about to smash into a test chAmber, Amber swerves out of the way and starts to slow down."
    GLaDOS "oh, thank science you're alive! In the absence of our communication, I presumed your demise."
    Marina "if Alice didn’t save us, we'd be dead right now!"
    "Amber flies to the central core chAmber, sets the RV down and everyone exits the RV."
    GLaDOS "How dreadfully has Kevin's schizophrenia deteriorated?"
    TF2Engie "he's done gone and lost his grasp on reality, teeterin' on the edge of downright instability."
    "Amber and Marina put Kevin down on a raised part of the floor."
    GLaDOS "Then the medication I've concocted for his ailment may not achieve optimal results. Nevertheless, I will administer the injection, as I do not have an alternative solution."
    "an arm carrying a needle appears out of the roof and injects Kevin."
    GLaDOS "The medication requires approximately thirty minutes to manifest its effects. Simultaneously, my sensors have identified a substantial rupture in the very fabric of your reality. Pray, elucidate on the circumstances leading to such an anomaly."
    Amber "it was a celestialsap-{nw}"
    Mariah "HOLD IT!"
    "Mariah shouts and the whole room falls silent."
    Mariah "that asshole took my sisters licence plate, some big buff star looking guy rips the sky in half, and now we're in some factory with a talking metal box! WHAT THE HELL IS GOING ON?!"
    GLaDOS "This \"metal box\" harbors a profound distaste for being relegated to a mere inanimate object."
    TF2Engie "your whole dang universe is in a heap of trouble. There's somethin' wreakin' havoc, spillin' damage into them neighborin' universes. We gotta fix that pronto."
    "suddenly a portal opens and a celestialsapien enters the central core chAmber."
    unknown_celestialsapien_1 "your actions are interfering with the process. the council has had enough of it. universe HB-05_ALTERNATE will be erased."
    unknown_man_2 "HOLD IT!"
    "suddenly Kevin stumbles towards the celestialsapien and almost falls before dell catches and holds him."
    Kevin "you can't erase their universe, the multiversal preservation act prohibits it! and like hell you forehead three pronged shits would violate it!"
    unknown_celestialsapien_1 "HB-05_ALTERNATE is causing damage to the surrounding universes. to prevent damage to other universes, it must be erased. the decision is final."
    Kevin "Section 87 subsection 5! \"In the event a universe is causing damage to others, the source of the damage must be investigated and if possible, destroyed or subdued, to prevent further damage.\""
    Kevin "and don't you DARE argue the details with me, I was there when the damn thing was written!"
    "the unknown celestialsapien  glares at Kevin."
    Kevin "I will prevent it from damaging other universes, you repair the surrounding universes and I’ll figure out why HB-05_ALTERNATE is causing damage."
    "the unknown celestialsapien continues his glare at Kevin."
    unknown_celestialsapien_1 "fine, it is in your capable hands."
    "the celestialsapien leaves and the portal closes."
    Kevin "ok um, if we could capture and hold the universe in something, we can stop it from damaging others."
    GLaDOS "A spherical enclave of compressed artificial space-time possesses the capacity to harbor an entire cosmos for a limited duration, yet we necessitate a power source of substantial magnitude to sustain such an endeavour."
    TF2Engie "A teeny-tiny quantum singularity danglin' on the brink of collapse oughta do the trick I reckon."
    Kevin "the InterdimensionalGregifcationTransportationCreation should have enough processing power to keep it stable while it's being transfured. let’s get to it."
    GLaDOS "Kevin, your current condition renders you unfit for the task at hand."
    Kevin "an entire universe is at stake here, I’ll be fine. these voices are annoying but I can ignore them."
    Kevin "GLaDOS, you create the space-time chAmber and power source. dell, you reconfigure a portal gun to open a portal to the space between worlds and create a capturing device."
    Kevin "I’ll reconfigure the InterdimensionalGregifcationTransportationCreation to be able to keep the universe stable. ready? break!"
    "all three of them run off to their assigned roles."
    Kevin "why the hell is the InterdimensionalGregifcationTransportationCreation integrated into a bloody 70's RV?! ahh I don't have time for this!"
    TF2Engie "I need a darn resonance re-sequencer in this spot, pronto!"
    GLaDOS "here! Kevin, elucidate the quantum frequencies you are configuring!"
    Kevin "19.675 MicroHertz! someone chuck over a wrench!"
    TF2Engie "here's yer wrench, partner! GLaDOS, reckon you could share the voltage on that there connector?"
    GLaDOS "17.65 volts AC!"
    Kevin "Greg’s done!"
    TF2Engie "The portal gun's all cooked up and ready to roll!"
    GLaDOS "The power source and chAmber have reached completion."
    "the gang starts connecting everything together."
    Kevin "you five stand back!"
    "the gang stands back as Kevin starts the machine up, it buzzes loudly. Kevin then shoots a portal and it opens to show the five's universe."
    Kevin "activating sucking!"
    "Kevin flicks a switch on the side of the portal gun and the universe starts to bend towards the gun and goes into it."
    Kevin "come on!"
    "the gun continues sucking until that entire universe is in the chAmber."
    GLaDOS "Initiating universe stabilization protocol."
    "the machine buzzes and sparks until a flash of blue light over comes it. HB-05_ALTERNATE is right there, in a sphere of glass."
    Kevin "heh heh. nice."
    GLaDOS "The designated universe has achieved stability status."
    TF2Engie "Well, I'll be hornswoggled! We done gone and pulled off the impossible, ain't that a sight to behold!"
    Tess "woah."
    Marina "is that our universe?"
    Kevin "yep. all that was, is and will be is right there. your birth, death and life are held right in there. downside is that it's not that easy to enter and exit without some scans of it in its current state, which ain't really possible..."
    Amber "hold on. if our universe is there, then it shouldn't be there when we entered it, or when we left it."
    TF2Engie "Well, darlin', that there's a paradox. Best not to wrangle too much with them thoughts."
    Amber "but it doesn't make sense!"
    Kevin "technically the entering and exiting did happen, it's just in a state of quantum uncertainty. it both did and didn't happen if that makes sense."
    Amber "it really doesn't."
    Kevin "quantum physics rarely does. anyways, get me up to speed with what’s happened so far."
    "everyone gets Kevin up to speed. GLaDOS, dell, the duo and the trio explain what has happened and introduces themselves."
    return