label Act6:
    Kevin "ok ummm. first off, sorry for stealing your licence plate kid. no clue why I became so fixated on it. second, we'll need to scan that universe for anything weird."
    Kevin "and thirdly, you activated a core?"
    GLaDOS "yes, I activated another core. but it is imperative that you engage in a period of rest, as the administered medication has exerted a toll on your body. I shall analyse the outcomes to facilitate further refinement."
    Kevin "can't argue with that, feels like my brain is alight in a vice... hell it's been a big day for all of us."
    Alice "I’ll arrange sleeping accommodations for our guests ma'am."
    GLaDOS "thank you Alice. Meanwhile, I shall take it upon myself to enlighten our visitors about the regulations governing this establishment."
    Joseph "this will be awhile wont it?"
    GLaDOS "correct."
    "GLaDOS explains to the gang the rules of the facility, Alice finishes up their accommodation and dell and Kevin catch up."
    GLaDOS "In conclusion, exercise utmost restraint and refrain from any unauthorized contact with our sophisticated machinery. The consequences of mishandling are rather dire, as certain devices have a penchant for terminating humans when subjected to improper usage."
    Mariah "why are you fucking with it then?"
    GLaDOS "A myriad of our perilous research endeavours has gracefully steered us towards extraordinary breakthroughs. for example, arkon radiation’s co-efficiency is near the theoretical limit that thermodynamics details."
    GLaDOS "it's properties may lead to more efficient power generation, storage and transferring technology. despite being deadly to biological matter."
    Tess "cool."
    GLaDOS "Indeed, if you require assistance, please ask Alice, me or another available core for help."
    Alice "accommodations are done!"
    GLaDOS "excellent. I would highly advise indulging in a brief respite. This directive extends to you as well, Kevin."
    Kevin "yeah yeah."
    TF2Engie "I'm fixin' to catch me some shut-eye too. Gonna let them notions simmer in my noggin while I'm catchin' some Z's."
    "everyone goes to their accommodations and Amber and Marina go the RV."
    Marina "hey Amber? do you think they'll be able to solve it?"
    Amber "I know they will Marina. but even if they don't, we're in this together, there's nobody else I’d choose to face this."
    Marina "awww Amber!"
    "night passes peacefully and morning comes. Marina is unusually up early and decides to see what GLaDOS is doing."
    "Marina exits the RV in her PJ's and comes across Kevin getting an injection."
    "Kevin fuck I hate needles."
    GLaDOS "Rest assured; the revised medication promises an extended duration of efficacy while mitigating any potential adverse effects."
    Kevin "is this what it was like back in the attached core days before your first death?"
    GLaDOS "While I am incapable of experiencing schizophrenia, the manifestations do bear a striking resemblance to my interactions with the attached cores."
    Kevin "life's never easy, is it?"
    GLaDOS "no, it is not."
    Marina "m-morning."
    Kevin "oh! hey Marina, didn't take you to be an early bird."
    Marina "no, I sleep in. I just had trouble sleeping last night."
    Kevin "I understand, a lotta shit happened and it's hard to keep sane after having your entire world turned upside down."
    Marina "what where you guys doing?"
    GLaDOS "we were engaged in a thorough medical examination of Kevin."
    Kevin "a lost mind doesn't just damage your psyche; it takes its toll on the body as well."
    Marina "you don't look like you slept well last night either."
    Kevin "I’ve always had insomnia, even as a child I never got a lot of sleep."
    TF2Engie "Mornin' there! How'd y'all rest last night?"
    Kevin "hey dell, same as always."
    Marina "not that great."
    TF2Engie "Don't you worry, Marina. We'll git ya back to base safe and sound, no doubt about it."
    Marina "thanks dell."
    "dell and Marina pull up a chair."
    TF2Engie "I've been wrackin' my brain tryin' to decipher how to scan that whole dang universe, but I ain't got nothin' yet. It's a real head-scratcher, I tell ya."
    Kevin "I haven't got anything either."
    GLaDOS "In the absence of its existence within the interdimensional realm, the multidimensional sensors remain unable to scan it."
    Marina "can't you just scan it right here with that sensor thing?"
    Kevin "that..."
    "Kevin, dell and GLaDOS think for a moment."
    Kevin "that might work...."
    TF2Engie "we got ourselves a universe all snug in a man-made bubble of space-time. Ain't no pesky dimensional barriers keeping them sensors from doin' their job!"
    GLaDOS "The approach to universe scanning remains unaltered; it's merely the targeted direction of the scan that has undergone adjustment."
    Kevin "if we point the sensors *directly* at the sphere, it can easily scan it!"
    Kevin "Marina you're a bloody genius!"
    "the trio get to work adjusting the sensors"
    GLaDOS "Commencing universe scan."
    Kevin "getting the data."
    "Kevin analyses the data and realises something."
    Kevin "holy shit... I stole that licence plate for a reason. it’s a universe anchor!"
    Marina "a what?"
    TF2Engie "Picture it like an anchor for a ship, holdin' it steady in the vast ocean. Now, imagine that same principle, but for a whole dang universe. Keeps everything in check, just like a trusty anchor."
    Kevin "if one from another universe gets into a universe it’s not supposed to then shit hits the fan. Also, fun fact, living beings can be one. Some girl called “Cassie” is one in your universe funnily enough."
    Kevin "anyways, using the data as a reference, I can modify the IGTC to get into that universe. Marina you'll come along just in case."
    Marina "okay"
    "Kevin modifies the IGTC"
    Kevin "alright, setting destination. when we find it, we'll destroy it."
    "the IGTC powers up and in a flash of white, they transport to Marina's universe, right where she first saw Kevin."
    Kevin "look around it should be here."
    "Kevin and Marina look for the plate."
    Kevin "found it! huh what a strange plate why does it say..."
    Kevin "has a look for horror."
    Kevin "oh god..."
    "Marina runs up panicked"
    Marina "what’s wrong?!"
    Kevin "shows Marina the licence plate, it has the words \"Heh heh heh heh\" on it."
    Kevin "why?! WHY THIS ANSWER?!?!"
    Marina "what answer?!"
    Kevin "THE ANSWER TO EXISTANCE!"
    Marina "what do you mean?!"
    Kevin "WE'RE IN A FAMILY GUY DREAM CUTAWAY GAG!!!!!"
    "suddenly the screen shrinks away showing neurons, bone and skin until we land on peter griffin who just woke up."
    Peter "Oh, Lois, you won't believe the crazy dream I had!"
    Lois "Peter, honey, just go to bed, okay? It's just a dream, not real life."
    peter "Lois, it felt so darn real. But, you know, I'll just shove it in the \"weird dreams I'm gonna forget\" drawer."
    return